// Services
export { BiDirectionalWorkflowEngine } from './BiDirectionalWorkflowEngine';
export { ChannelAutoCreationService, channelAutoCreationService } from './ChannelAutoCreationService';
export { DecentralizedChatService } from './DecentralizedChatService';
export { DocumentWorkflowIntegration } from './DocumentWorkflowIntegration';
export type { DocumentWorkflowEvent, WorkflowNotification } from './DocumentWorkflowIntegration';
export { emergencyNotificationService } from './EmergencyNotificationService';
export { escalationService } from './EscalationService';
export { ExternalNotificationDispatcher } from './ExternalNotificationDispatcher';
export type { NotificationPreferences, NotificationContent } from './ExternalNotificationDispatcher';
export { GoogleMeetService } from './GoogleMeetService';
export { liveMeetingService } from './LiveMeetingService';
export { MeetingAPIService, meetingAPI } from './MeetingAPIService';
export { MockMeetingService, mockMeetingService } from './MockMeetingService';
export { notificationService } from './NotificationService';
export { realTimeDocumentService } from './RealTimeDocumentService';
export type { DocumentData } from './RealTimeDocumentService';
export { ZoomService } from './ZoomService';
export { AISignaturePlacementService, aiSignaturePlacement } from './aiSignaturePlacement';
export type { SignatureZone, DocumentAnalysis } from './aiSignaturePlacement';
export { apiService } from './api';
export { BlockchainSignatureService, getBlockchainService } from './blockchainSignatureService';
export { GeminiAIService, geminiAI } from './geminiAI';
